work_dir = "examples/openssl/modes-cbc"
name = "modes-cbc-vpaes"
target_syms = ["sym.vpaes_cbc_encrypt", "sym.vpaes_cbc_decrypt"]
exec_command = "/usr/bin/timeout"
exec_args = ["30", "./bin"]
dry_run = false
