work_dir = "examples/libgcrypt/aes"
name = "aes-aesni"
target_syms = [
    "sym._gcry_aes_aesni_encrypt",
    "sym._gcry_aes_aesni_do_setkey",
    "sym._gcry_aes_aesni_decrypt",
]
exec_command = "/usr/bin/timeout"
exec_args = ["30", "./bin"]
dry_run = false
