work_dir = "examples/libgcrypt/modes-cbc"
name = "modes-cbc-armv8"
target_syms = ["sym._gcry_aes_cbc_enc_armv8_ce", "sym._gcry_aes_cbc_dec_armv8_ce"]
exec_command = "/usr/bin/timeout"
exec_args = ["30", "./bin"]
dry_run = false
