work_dir = "examples/mbedtls/aes"
name = "aes-aesni"
target_syms = [
    "sym.mbedtls_aesni_crypt_ecb",
    "sym.mbedtls_aesni_setkey_enc",
    "sym.mbedtls_aesni_inverse_key",
    "sym.aesni_setkey_enc_128",
]
exec_command = "/usr/bin/timeout"
exec_args = ["30", "./bin"]
dry_run = false
