work_dir = "examples/mbedtls/modes-ctr"
name = "modes-ctr"
target_syms = [
    "sym.aes_crypt_ctr_wrap",
    "sym.mbedtls_aes_crypt_ctr",
]
exec_command = "/usr/bin/timeout"
exec_args = ["30", "./bin"]
dry_run = false
