work_dir = "examples/libressl/aes"
name = "aes-ecb"
target_syms = [
    "sym.AES_set_decrypt_key",
    "sym.AES_set_encrypt_key",
    "sym.AES_encrypt",
]
exec_command = "/usr/bin/timeout"
exec_args = ["30", "./bin"]
dry_run = false
