work_dir = "examples/libressl/modes-cbc"
name = "modes-cbc"
target_syms = ["sym.CRYPTO_cbc128_encrypt", "sym.CRYPTO_cbc128_decrypt"]
exec_command = "/usr/bin/timeout"
exec_args = ["30", "./bin"]
dry_run = false
